#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
frontend:
updater:
  reporting: false
sun:
discovery:
config:
person:
system_health:
mobile_app:
ssdp:
zeroconf:
map:
stream:
http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  #ip_ban_enabled: true
  #login_attempts_threshold: 10

#################################################################
## Components
#################################################################

hue:
  bridges:
    - host: REDACTED.2
      allow_hue_groups: false
      allow_unreachable: true

lutron_caseta:
    host: REDACTED.4
    keyfile: !secret lutron_keyfile
    certfile: !secret lutron_certfile
    ca_certs: !secret lutron_cacerts

vera:
  vera_controller_url: http://REDACTED.3:3480/
  exclude: [ 19]

lifx:
  light:
    - server: REDACTED.105
      port: 56700
      broadcast: REDACTED.125

sonos:
  media_player:
    hosts:
      - REDACTED.201
      - REDACTED.202
      - REDACTED.203
      - REDACTED.204
      - REDACTED.205
      - REDACTED.206
      - REDACTED.207
      - REDACTED.208
      - REDACTED.209
      - REDACTED.210
      - REDACTED.211
      - REDACTED.212
      - REDACTED.213

wemo:
  discovery: false
  static:
#    - REDACTED.50
#    - REDACTED.51
    - REDACTED.52
    - REDACTED.54
    - REDACTED.55
    - REDACTED.79

media_player:
  - platform: yamaha
    name: "Media Center Receiver"
    host: REDACTED.10
    source_ignore:
      - "AUX"
      - "AV1"
      - "AV2"
      - "AV3"
      - "Bluetooth"
      - "Deezer"
      - "MusicCast Link"
      - "NET RADIO"
      - "Pandora"
      - "SERVER"
      - "Spotify"
      - "TIDAL"
      - "TUNER"
      - "USB"
    source_names:
      HDMI1: "Apple TV"
      HDMI2: "Xbox One X"
      HDMI3: "Nintendo Switch"
      HDMI4: "Wii U"
      AUDIO1: "TV Audio"
      AUDIO2: "Sonos Digital"
      AUDIO3: "Sonos"

remote:
  - platform: harmony
    name: Media Center
    host: REDACTED.5
    activity: Watch TV
  - platform: harmony
    name: Bedroom TV
    host: REDACTED.6
    activity: Watch TV
  - platform: harmony
    name: Office TV
    host: REDACTED.7
    activity: Watch TV

camera:
  - platform: generic
    name: Front Porch
    still_image_url: https://REDACTED.11/snap.jpeg
    stream_source: rtsp://REDACTED.3:7447/REDACTED
    verify_ssl: false
  - platform: generic
    name: Driveway
    still_image_url: https://REDACTED.6/snap.jpeg
    stream_source: rtsp://REDACTED.3:7447/REDACTED
    verify_ssl: false
  - platform: generic
    name: Garage
    still_image_url: https://REDACTED.7/snap.jpeg
    stream_source: rtsp://REDACTED.3:7447/REDACTED
    verify_ssl: false
  - platform: generic
    name: Backyard Gate
    still_image_url: https://REDACTED.9/snap.jpeg
    stream_source: rtsp://REDACTED.3:7447/REDACTED
    verify_ssl: false
  - platform: generic
    name: Side Yard
    still_image_url: https://REDACTED.10/snap.jpeg
    stream_source: rtsp://REDACTED.3:7447/REDACTED
    verify_ssl: false
  - platform: generic
    name: Backyard
    still_image_url: https://REDACTED.8/snap.jpeg
    stream_source: rtsp://REDACTED.3:7447/REDACTED
    verify_ssl: false
  - platform: generic
    name: Basement
    still_image_url: https://REDACTED.12/snap.jpeg
    stream_source: rtsp://REDACTED.3:7447/REDACTED
    verify_ssl: false
  - platform: generic
    name: Living Room
    still_image_url: https://REDACTED.13/snap.jpeg
    stream_source: rtsp://REDACTED.3:7447/yb1q1StMMJm4y3D9
    verify_ssl: false

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key

google:
  client_id: !secret google_client_id
  client_secret: !secret goole_client_secret
  track_new_calendar: true

vacuum:
  - platform: roomba
    host: REDACTED.8
    username: !secret downstairs_roomba_username
    password: !secret downstairs_roomba_password
    name: Downstairs Roomba
  - platform: roomba
    host: REDACTED.9
    username: !secret upstairs_roomba_username
    password: !secret upstairs_roomba_password
    name: Upstairs Roomba

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily
    name: "REDACTED, MO"

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: US
  devices:
    - device_id: !secret dyson_id
      device_ip: REDACTED.11

alarm_control_panel:
  - platform: manual
    name: Alarm
    code_arm_required: false
    pending_time: 30
    delay_time: 30
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      delay_time: 30
      trigger_time: 60
      pending_time: 30
    armed_away:
      delay_time: 15
      trigger_time: 120
      pending_time: 30

pi_hole:
  - host: 'REDACTED.4'
    name: 'Primary Pi-Hole'
    api_key: !secret primary_pi_hole_api_key
  - host: 'REDACTED.5'
    name: 'Secondary Pi-Hole'
    api_key: !secret secondary_pi_hole_api_key

hacs:
  token: !secret githubtoken
  sidepanel_title: Community
  sidepanel_icon: mdi:alpha-c-box
  appdaemon: false
  python_script: false

route53:
  aws_access_key_id: !secret aws_access_key_id_route53
  aws_secret_access_key: !secret aws_secret_access_key_route53
  zone: !secret aws_zone_route53
  domain: !secret aws_domain_route53
  records:
    - home

#################################################################
## Includes
#################################################################

automation: !include_dir_merge_list automation
recorder: !include recorder.yaml
logbook: !include logbook.yaml
history: !include history.yaml
group: !include groups.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
script: !include scripts.yaml
light: !include light_group.yaml
homekit: !include homekit.yaml
ios: !include ios.yaml
switch: !include switch.yaml
emulated_hue: !include emulated_hue.yaml
