#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  customize: !include customize.yaml
default_config:
updater:
  reporting: false
discovery:
stream:
http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

#################################################################
## Components
#################################################################

hue:
  bridges:
    - host: REDACTED.2
      allow_hue_groups: false
      allow_unreachable: true

lutron_caseta:
    host: 'lutron.network.REDACTED'
    keyfile: !secret lutron_keyfile
    certfile: !secret lutron_certfile
    ca_certs: !secret lutron_cacerts

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: US
  devices:
    - device_id: !secret dyson_id
      device_ip: 'REDACTED-office-fan.network.REDACTED'

wemo:
  discovery: true
  static:
    - 'att-router-switch.network.REDACTED'
    - 'REDACTED-office-air-purifier.network.REDACTED'
    - 'lower-backyard-lighting.network.REDACTED'
    - 'USER2-office-desk-lamp.network.REDACTED'

media_player:
  - platform: yamaha
    name: "Surround Sound Receiver"
    host: 'receiver.network.REDACTED'
    source_ignore:
      - "AUX"
      - "AV1"
      - "AV2"
      - "AV3"
      - "Bluetooth"
      - "Deezer"
      - "MusicCast Link"
      - "NET RADIO"
      - "Pandora"
      - "SERVER"
      - "Spotify"
      - "TIDAL"
      - "TUNER"
      - "USB"
    source_names:
      HDMI1: "Apple TV"
      HDMI2: "Xbox One X"
      HDMI3: "Nintendo Switch"
      HDMI4: "Wii U"
      AUDIO1: "TV Audio"
      AUDIO2: "Sonos Digital"
      AUDIO3: "Sonos"

camera:
  - platform: generic
    name: Front Porch
    still_image_url: https://front-porch-camera.network.REDACTED/snap.jpeg
    stream_source: rtsp://cloudkey.network.REDACTED:7447/REDACTED
    verify_ssl: false
  - platform: generic
    name: Driveway
    still_image_url: https://driveway-camera.network.REDACTED/snap.jpeg
    stream_source: rtsp://cloudkey.network.REDACTED:7447/REDACTED
    verify_ssl: false
  - platform: generic
    name: Garage
    still_image_url: https://garage-camera.network.REDACTED/snap.jpeg
    stream_source: rtsp://cloudkey.network.REDACTED:7447/REDACTED
    verify_ssl: false
  - platform: generic
    name: Backyard Gate
    still_image_url: https://backyard-gate-camera.network.REDACTED/snap.jpeg
    stream_source: rtsp://cloudkey.network.REDACTED:7447/REDACTED
    verify_ssl: false
  - platform: generic
    name: Side Yard
    still_image_url: https://side-yard-camera.network.REDACTED/snap.jpeg
    stream_source: rtsp://cloudkey.network.REDACTED:7447/REDACTED
    verify_ssl: false
  - platform: generic
    name: Backyard
    still_image_url: https://backyard-camera.network.REDACTED/snap.jpeg
    stream_source: rtsp://cloudkey.network.REDACTED:7447/REDACTED
    verify_ssl: false
  - platform: generic
    name: Basement
    still_image_url: https://basement-camera.network.REDACTED/snap.jpeg
    stream_source: rtsp://cloudkey.network.REDACTED:7447/REDACTED
    verify_ssl: false
  - platform: generic
    name: Living Room
    still_image_url: https://living-room-camera.network.REDACTED/snap.jpeg
    stream_source: rtsp://cloudkey.network.REDACTED:7447/yb1q1StMMJm4y3D9
    verify_ssl: false

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key

google:
  client_id: !secret google_client_id
  client_secret: !secret goole_client_secret
  track_new_calendar: true

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily
    name: "REDACTED, MO"

alarm_control_panel:
  - platform: manual
    name: Alarm
    code_arm_required: false
    arming_time: 30
    delay_time: 30
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      delay_time: 30
      trigger_time: 60
      arming_time: 30
    armed_away:
      delay_time: 15
      trigger_time: 120
      arming_time: 30

hacs:
  token: !secret githubtoken
  sidepanel_title: Community Store
  sidepanel_icon: mdi:home-assistant
  appdaemon: false
  python_script: false

route53:
  aws_access_key_id: !secret aws_access_key_id_route53
  aws_secret_access_key: !secret aws_secret_access_key_route53
  zone: !secret aws_zone_route53
  domain: !secret aws_domain_route53
  records:
    - home

influxdb:
  host: 'influxdb.network.REDACTED'
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  include:
    entities:
      - climate.main_floor
      - climate.office_fan
      - sensor.living_room_temperature
      - sensor.main_floor_temperature
      - sensor.kitchen_temperature
      - sensor.bedroom_temperature
      - sensor.bathroom_temperature
      - sensor.office_temperature
      - sensor.USER2_office_temperature
      - sensor.guest_bedroom_temperature
      - sensor.basement_temperature
      - sensor.laundry_room_temperature
      - sensor.garage_temperature
      - sensor.main_floor_humidity
      - sensor.office_fan_humidity
      - sensor.REDACTED_humidity
      - sensor.REDACTED_temperature
      - sensor.nas_status
      - sensor.nas_smart_status_drive_0_1
      - sensor.nas_smart_status_drive_0_2
      - sensor.nas_smart_status_drive_0_3
      - sensor.nas_smart_status_drive_0_4
      - sensor.nas_cpu_usage
      - sensor.nas_memory_usage
      - sensor.nas_volume_used_storage
      - sensor.nas_system_temperature
      - sensor.uptime
      - sensor.ups_status
      - sensor.ups_battery_runtime_mins
      - sensor.ups_input_voltage
      - sensor.ups_battery_charge

#################################################################
## Includes
#################################################################

automation: !include_dir_merge_list automation
recorder: !include recorder.yaml
logbook: !include logbook.yaml
history: !include history.yaml
group: !include groups.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
script: !include scripts.yaml
light: !include light_group.yaml
homekit: !include homekit.yaml
ios: !include ios.yaml
switch: !include switch.yaml
emulated_hue: !include emulated_hue.yaml
