#################################################################
## Home Assistant
#################################################################

homeassistant:
  name: Home
  latitude: REDACTED
  longitude: REDACTED
  elevation: REDACTED
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

frontend:
updater:
  reporting: no
sun:
conversation:
discovery:
  ignore:
    - apple_tv
    - sonos
    - harmony
config:

http:
  api_password: REDACTED
  ssl_certificate: /etc/letsencrypt/live/REDACTED/REDACTED
  ssl_key: /etc/letsencrypt/live/REDACTED/REDACTED
  base_url: REDACTED
  trusted_networks:
    - 127.0.0.1
    - REDACTED.0/24
    - REDACTED.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 3

#################################################################
## Components
#################################################################

ecobee:
  api_key: REDACTED

hue:
  bridges:
    - host: REDACTED.106
      allow_hue_groups: false
      allow_unreachable: true

emulated_hue:
  host_ip: REDACTED.105
  listen_port: 8300
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: false

media_player:
  - platform: plex
    entity_namespace: 'plex'
  - platform: sonos
    hosts:
      - REDACTED.200
      - REDACTED.201
      - REDACTED.202
      - REDACTED.203
      - REDACTED.204
      - REDACTED.205
      - REDACTED.206
      - REDACTED.208
      - REDACTED.209
      - REDACTED.210
  - platform: roku

apple_tv:
  - name: Living Room Apple TV
    host: REDACTED.150
    login_id: REDACTED
    start_off: false
  - name: Guest Bedroom Apple TV
    host: REDACTED.153
    login_id: REDACTED
    start_off: false
  - name: Bedroom Apple TV
    host: REDACTED.152
    login_id: REDACTED
    start_off: false
  - name: USER1's Office Apple TV
    host: REDACTED.151
    login_id: REDACTED
    start_off: false

remote:
  - platform: harmony
    name: Media Center
    host: REDACTED.109
    activity: Watch TV
  - platform: harmony
    name: Bedroom TV
    host: REDACTED.247
    activity: Watch TV

ios:

map:

wemo:
  static:
    - REDACTED.111
    - REDACTED.112
    - REDACTED.113
    - REDACTED.115

switch:
  - platform: tplink
    host: REDACTED.114
    name: MyQ Garage Outlet

ifttt:
  key: REDACTED

device_tracker:
  - platform: unifi
    username: REDACTED
    password: REDACTED
    host: REDACTED.3
    verify_ssl: false
    consider_home: 180
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False
  - platform: locative

cover:
  - platform: myq
    username: REDACTED
    password: REDACTED
    type: chamberlain
  - platform: wink
    entity_namespace: wink

ring:
    username: REDACTED
    password: REDACTED

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion

camera:
  - platform: uvc
    nvr: REDACTED.99
    key: REDACTED
    password: REDACTED
  - platform: foscam
    ip: REDACTED.107
    name: Garage Interior
    port: REDACTED
    username: REDACTED
    password: REDACTED
  - platform: generic
    still_image_url: https://icons.wxug.com/data/weather-maps/radar/united-states/jefferson-city-missouri-region-current-radar-animation.gif
    name: MO Weather Radar

tts:
  - platform: amazon_polly
    aws_access_key_id: 'REDACTED'
    aws_secret_access_key: 'REDACTED'

google:
  client_id: REDACTED
  client_secret: REDACTED
  track_new_calendar: true

wink:

vacuum:
  - platform: roomba
    host: REDACTED.228
    username: REDACTED
    password: REDACTED

#################################################################
## Includes
#################################################################

automation: !include_dir_merge_list automation
recorder: !include recorder.yaml
logbook: !include logbook.yaml
history: !include history.yaml
zone: !include zones.yaml
group: !include groups.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
script: !include scripts.yaml
weblink: !include weblinks.yaml
light: !include light_group.yaml
