#################################################################
## Bedtime Automations
#################################################################

        ##########################################################
        ## Bedtime
        ##########################################################

- alias: Bedtime

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'

  action:
    - service: lock.lock
      entity_id:
       - lock.front_door
       - lock.back_door
       - lock.basement_door
    - service: light.turn_off
      entity_id:
        - group.interior_lights
        - light.backyard_deck
        - light.backyard_patio
        - light.garage_interior
    - service: switch.turn_off
      entity_id:
        - switch.air_purifier
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting
        - switch.fireplace
        - switch.basement_heater
    - service: fan.turn_off
      entity_id:
        - fan.office_fan
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.interior_holiday
        - input_boolean.office_rainbow
        - input_boolean.livingroom_rainbow
        - input_boolean.bedroom_rainbow
        - input_boolean.front_porch_rainbow
        - input_boolean.pop_music
        - input_boolean.jazz_music
        - input_boolean.chill_music
        - input_boolean.electronic_music
        - input_boolean.classical_music
        - input_boolean.adele_music
        - input_boolean.group_all_sonos
    - service: input_select.select_option
      data:
        entity_id: input_select.remote
        option: "PowerOff"
    - service: input_select.select_option
      data:
        entity_id: input_select.sonos
        option: "None"
    - service: media_player.media_stop
      entity_id:
        - media_player.sonos_surround_sound
        - media_player.sonos_living_room
        - media_player.sonos_dining_room
        - media_player.sonos_kitchen
        - media_player.sonos_bathroom
        - media_player.sonos_bedroom
        - media_player.sonos_USER1s_office
        - media_player.sonos_USER1s_office_move
        - media_player.sonos_USER2s_office
        - media_player.sonos_move
        - media_player.sonos_backyard_patio
    - delay: '00:00:60'
    - service: light.turn_off
      entity_id:
        - light.backyard_patio
        - light.backyard_deck
        - light.garage_interior

        ##########################################################
        ## Bedtime Guest Mode
        ##########################################################

- alias: Bedtime - Guest Mode

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'

  action:
    - service: lock.lock
      entity_id:
       - lock.front_door
       - lock.back_door
       - lock.basement_door
    - service: light.turn_off
      entity_id:
        - group.interior_lights
        - light.backyard_deck
        - light.backyard_patio
        - light.garage_interior
    - service: switch.turn_off
      entity_id:
        - switch.air_purifier
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting
        - switch.fireplace
        - switch.basement_heater
    - service: fan.turn_off
      entity_id:
        - fan.office_fan
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.interior_holiday
        - input_boolean.office_rainbow
        - input_boolean.livingroom_rainbow
        - input_boolean.bedroom_rainbow
        - input_boolean.front_porch_rainbow
        - input_boolean.pop_music
        - input_boolean.jazz_music
        - input_boolean.chill_music
        - input_boolean.electronic_music
        - input_boolean.classical_music
        - input_boolean.adele_music
        - input_boolean.group_all_sonos
    - service: input_select.select_option
      data:
        entity_id: input_select.remote
        option: "PowerOff"
    - service: input_select.select_option
      data:
        entity_id: input_select.office_remote
        option: "PowerOff"
    - service: input_select.select_option
      data:
        entity_id: input_select.sonos
        option: "None"
    - service: media_player.media_stop
      entity_id:
        - media_player.sonos_surround_sound
        - media_player.sonos_living_room
        - media_player.sonos_dining_room
        - media_player.sonos_kitchen
        - media_player.sonos_bathroom
        - media_player.sonos_bedroom
        - media_player.sonos_USER1s_office
        - media_player.sonos_USER1s_office_move
        - media_player.sonos_USER2s_office
        - media_player.sonos_move
        - media_player.sonos_backyard_patio
    - service: climate.set_preset_mode
      data:
        entity_id: climate.main_floor
        preset_mode: 'smart3'
    - delay: '00:00:60'
    - service: light.turn_off
      entity_id:
        - light.backyard_patio
        - light.backyard_deck
        - light.garage_interior

        ##########################################################
        ## Bedtime Before 11:30p
        ##########################################################

- alias: Bedtime - Before 11:30p

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.thermostat_away
      state: 'off'
    - condition: time
      after: '17:00'
      before: '23:30'

  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.main_floor
        preset_mode: 'sleep'

        ##########################################################
        ## Bedtime after Midnight
        ##########################################################

- alias: Bedtime - After Midnight

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 0

  condition:
    - condition: time
      after: '00:00'
      before: '06:00'
    - condition: state
      entity_id: input_select.holiday
      state: 'None'

  action:
    - service: light.turn_off
      entity_id:
        - light.front_porch
        - light.back_door
        - light.garage_light
        - light.backyard_patio
        - light.backyard_deck
        - light.garage_interior
    - service: switch.turn_off
      entity_id:
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting
    - delay: '00:00:60'
    - service: light.turn_off
      entity_id:
        - light.backyard_patio
        - light.backyard_deck
        - light.garage_interior

        ##########################################################
        ## Bedtime after Midnight Holiday
        ##########################################################

- alias: Bedtime - After Midnight Holiday

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 0

  condition:
    - condition: time
      after: '00:00'
      before: '07:30'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.holiday
          state: 'Halloween'
        - condition: state
          entity_id: input_select.holiday
          state: "St. Patrick's Day"
        - condition: state
          entity_id: input_select.holiday
          state: 'Easter'
        - condition: state
          entity_id: input_select.holiday
          state: "Valentine's Day"
        - condition: state
          entity_id: input_select.holiday
          state: 'Thanksgiving'
        - condition: state
          entity_id: input_select.holiday
          state: 'Labor Day'
        - condition: state
          entity_id: input_select.holiday
          state: 'Memorial Day'
        - condition: state
          entity_id: input_select.holiday
          state: 'Independence Day'
        - condition: state
          entity_id: input_select.holiday
          state: 'Veterans Day'
        - condition: state
          entity_id: input_select.holiday
          state: 'Christmas'

  action:
    - service: light.turn_off
      entity_id:
        - light.back_door
        - light.garage_light
        - light.backyard_patio
        - light.backyard_deck
        - light.garage_interior
    - service: switch.turn_off
      entity_id:
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting

        ##########################################################
        ## Bedtime Close Garage if Open
        ##########################################################

- alias: Bedtime - Bedtime Close Garage if Open

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: cover.garage_door
      state: 'open'

  action:
    - service: light.turn_on
      entity_id:
        - light.garage_interior
      data:
       flash: long
    - delay: '00:00:15'
    - service: cover.close_cover
      entity_id: cover.garage_door


        ##########################################################
        ## Reset Bedtime Switch
        ##########################################################

- alias: Bedtime - Reset Switch

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 6
        seconds: 0

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.bedtime
