        ##########################################################
        ## Christmas Tree Away Mode
        ##########################################################

- alias: Christmas - Tree Away Mode

  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Christmas Tree Home Mode
        ##########################################################

- alias: Christmas - Tree Home Mode

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.USER1_away
        state: 'on'
      - condition: state
        entity_id: input_boolean.USER2_away
        state: 'on'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Turn on Christmas Tree at Sunset
        ##########################################################

- alias: Christmas - Turn on Christmas Tree at Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:30:00'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_interior_lights_sunset
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Turn on Christmas Tree when USER2 Home
        ##########################################################

- alias: Christmas - Turn on Tree when USER2 Home

  trigger:
    - platform: time
      at: '08:30'

  condition:
    - condition: state
      entity_id: device_tracker.USER2DEVICE
      state: 'home'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Turn off Christmas Tree when USER2 Leaves
        ##########################################################

- alias: Christmas - Turn off Tree when USER2 Leaves

  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: time
      after: '05:00'
      before: '15:00'
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'home'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Turn on Christmas Tree when USER2 Home
        ##########################################################

- alias: Christmas - Turn on Christmas Tree when USER2 Home

  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'not_home'
      to: 'home'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: time
      after: '08:30'
      before: '13:00'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER2_away
      state: 'on'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Turn on Christmas Tree at 5a if USER2 Home and Working
        ##########################################################

- alias: Christmas - Turn on Tree at 5a if USER2 Home and Working

  trigger:
    - platform: time
      at: '05:00'

  condition:
    - condition: state
      entity_id: device_tracker.USER2DEVICE
      state: 'home'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_lights_morning
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER2_working
      state: 'on'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Plex Stopped Playing Christmas Tree on
        ##########################################################

- alias: Christmas - Plex Stopped Playing Tree on

  trigger:
    - platform: state
      entity_id: media_player.plex_living_room
      to: 'paused'
      for:
        hours: 0
        minutes: 3
        seconds: 0
    - platform: state
      entity_id: media_player.plex_living_room
      to: 'idle'
      for:
        hours: 0
        minutes: 3
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Plex Playing Christmas Tree on
        ##########################################################

- alias: Christmas - Plex Playing Tree on

  trigger:
    - platform: state
      entity_id: media_player.plex_living_room
      to: 'playing'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Late Night TV Watching before Midnight Christmas Tree on
        ##########################################################

- alias: Christmas - Late Night TV Watching before Midnight Tree on

  trigger:
    - platform: state
      entity_id: media_player.living_room_apple_tv
      to: 'paused'
      for:
        hours: 0
        minutes: 3
        seconds: 0
    - platform: state
      entity_id: media_player.living_room_apple_tv
      to: 'idle'
      for:
        hours: 0
        minutes: 3
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: time
      after: '21:30'
    - condition: state
      entity_id: input_boolean.watching_plex
      state: 'off'
    - condition: state
      entity_id: input_select.remote
      state: 'Watch TV'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Late Night TV Watching after Midnight Christmas Tree on
        ##########################################################

- alias: Christmas - Late Night TV Watching after Midnight Tree on

  trigger:
    - platform: state
      entity_id: media_player.living_room_apple_tv
      to: 'paused'
      for:
        hours: 0
        minutes: 3
        seconds: 0
    - platform: state
      entity_id: media_player.living_room_apple_tv
      to: 'idle'
      for:
        hours: 0
        minutes: 3
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: time
      after: '00:00'
      before: '03:00'
    - condition: state
      entity_id: input_boolean.watching_plex
      state: 'off'
    - condition: state
      entity_id: input_select.remote
      state: 'Watch TV'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Late Night TV Watching after Midnight Christmas Tree On
        ##########################################################

- alias: Christmas - Late Night TV Watching after Midnight Tree On

  trigger:
    - platform: state
      entity_id: media_player.living_room_apple_tv
      to: 'paused'
      for:
        hours: 0
        minutes: 3
        seconds: 0
    - platform: state
      entity_id: media_player.living_room_apple_tv
      to: 'idle'
      for:
        hours: 0
        minutes: 3
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: time
      after: '00:00'
      before: '03:00'
    - condition: state
      entity_id: input_boolean.watching_plex
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Late Night TV Watching after Midnight Christmas Tree off
        ##########################################################

- alias: Christmas - Late Night TV Watching after Midnight Tree off

  trigger:
    - platform: state
      entity_id: media_player.living_room_apple_tv
      to: 'playing'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: time
      after: '00:00'
      before: '03:00'
    - condition: state
      entity_id: input_boolean.watching_plex
      state: 'off'
    - condition: state
      entity_id: input_select.remote
      state: 'Watch TV'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Late Night TV Watching before Midnight Christmas Tree Off
        ##########################################################

- alias: Christmas - Late Night TV Watching before Midnight Tree Off

  trigger:
    - platform: state
      entity_id: media_player.living_room_apple_tv
      to: 'playing'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: time
      after: '21:30'
    - condition: state
      entity_id: input_boolean.watching_plex
      state: 'off'
    - condition: state
      entity_id: input_select.remote
      state: 'Watch TV'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Christmas Tree Bedtime
        ##########################################################

- alias: Christmas - Tree Bedtime

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree
