#################################################################
## Christmas Automations
#################################################################

        ##########################################################
        ## Turn on Exterior Christmas Lights at Sunset
        ##########################################################

- alias: Christmas - Turn on Exterior Christmas Lights at Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:15:00'

  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_on_sunset
      state: 'off'
    - condition: state
      entity_id: input_select.holiday
      state: 'Christmas'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.exterior_christmas_lights

        ##########################################################
        ## Turn Off Exterior Christmas Lights at 2a
        ##########################################################

- alias: Christmas - Turn Off Exterior Christmas Lights at 2a

  trigger:
   - platform: time
     at: '02:00'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.exterior_christmas_lights

        ##########################################################
        ## Turn Off Exterior Christmas Lights at Sunrise
        ##########################################################

- alias: Christmas - Turn Off Exterior Christmas Lights at Sunrise

  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '+00:15:00'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.exterior_christmas_lights

        ##########################################################
        ## Turn off Christmas Lights after 2a
        ##########################################################

- alias: Christmas - Turn off Christmas Lights after 2a

  trigger:
    - platform: state
      entity_id: switch.exterior_christmas_lights
      from: 'off'
      to: 'on'
      for:
        hours: 1
        minutes: 0
        seconds: 0

  condition:
    - condition: time
      after: '02:00'
      before: '07:30'
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.exterior_christmas_lights

        ##########################################################
        ## Turn on Christmas Lights when Home
        ##########################################################

- alias: Christmas - Turn on Christmas Lights when Home

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: switch.exterior_christmas_lights
      state: 'off'
    - condition: state
      entity_id: input_select.holiday
      state: 'Christmas'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.USER1_away
          state: 'on'
        - condition: state
          entity_id: input_boolean.USER2_away
          state: 'on'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.exterior_christmas_lights
