#################################################################
## Fan Automations
#################################################################

#################################################################
## Pico Remotes
#################################################################

  #################################################################
  ## Living Room Fans On Pico Remote
  #################################################################

- alias: Fan - Living Room Fans On Pico Remote

  trigger:
    - platform: state
      entity_id: sensor.living_room_fan_remote
      to: '2'

  condition:
    - condition: state
      entity_id: group.living_room_fans
      state: 'off'

  action:
    - service: fan.turn_on
      entity_id:
        - fan.living_room_east
        - fan.living_room_west
    - delay:
        seconds: 1

  #################################################################
  ## Living Room Fans Off Pico Remote
  #################################################################

- alias: Fan - Living Room Fans Off Pico Remote

  trigger:
    - platform: state
      entity_id: sensor.living_room_fan_remote
      to: '2'

  condition:
    - condition: state
      entity_id: group.living_room_fans
      state: 'on'

  action:
    - service: fan.turn_off
      entity_id:
        - fan.living_room_east
        - fan.living_room_west
    - delay:
        seconds: 1

  #################################################################
  ## Living Room Fans Off to On Pico Remote Raise or Lower
  #################################################################

- alias: Fan - Living Room Fans Off to On Pico Remote Raise or Lower

  trigger:
    - platform: state
      entity_id: sensor.living_room_fan_remote
      to: '8'
    - platform: state
      entity_id: sensor.living_room_fan_remote
      to: '16'

  condition:
    - condition: state
      entity_id: group.living_room_fans
      state: 'off'

  action:
    - service: fan.turn_on
      entity_id:
        - fan.living_room_east
        - fan.living_room_west
    - delay:
        seconds: 1

  #################################################################
  ## Living Room Fans Low to Med Pico Remote Raise
  #################################################################

- alias: Fan - Living Room Fans Low to Med Pico Remote Raise

  trigger:
    - platform: state
      entity_id: sensor.living_room_fan_remote
      to: '8'

  condition:
    - condition: state
      entity_id: group.living_room_fans
      state: 'on'
    - condition: or
      conditions:
      - condition: template
        value_template: "{%if is_state_attr('fan.living_room_east', 'speed', 'low') %}true{%endif%}"
      - condition: template
        value_template: "{%if is_state_attr('fan.living_room_west', 'speed', 'low') %}true{%endif%}"

  action:
    - service: fan.set_speed
      data:
        entity_id:
          - fan.living_room_east
          - fan.living_room_west
        speed: medium
    - delay:
        seconds: 1

  #################################################################
  ## Living Room Fans Med to High Pico Remote Raise
  #################################################################

- alias: Fan - Living Room Fans Med to High Pico Remote Raise

  trigger:
    - platform: state
      entity_id: sensor.living_room_fan_remote
      to: '8'

  condition:
    - condition: state
      entity_id: group.living_room_fans
      state: 'on'
    - condition: or
      conditions:
      - condition: template
        value_template: "{%if is_state_attr('fan.living_room_east', 'speed', 'medium') %}true{%endif%}"
      - condition: template
        value_template: "{%if is_state_attr('fan.living_room_west', 'speed', 'medium') %}true{%endif%}"

  action:
    - service: fan.set_speed
      data:
        entity_id:
          - fan.living_room_east
          - fan.living_room_west
        speed: high
    - delay:
        seconds: 1

  #################################################################
  ## Living Room Fans High to Med Pico Remote Lower
  #################################################################

- alias: Fan - Living Room Fans High to Med Pico Remote Lower

  trigger:
    - platform: state
      entity_id: sensor.living_room_fan_remote
      to: '16'

  condition:
    - condition: state
      entity_id: group.living_room_fans
      state: 'on'
    - condition: or
      conditions:
      - condition: template
        value_template: "{%if is_state_attr('fan.living_room_east', 'speed', 'high') %}true{%endif%}"
      - condition: template
        value_template: "{%if is_state_attr('fan.living_room_west', 'speed', 'high') %}true{%endif%}"

  action:
    - service: fan.set_speed
      data:
        entity_id:
          - fan.living_room_east
          - fan.living_room_west
        speed: medium
    - delay:
        seconds: 1

  #################################################################
  ## Living Room Fans Med to Low Pico Remote Lower
  #################################################################

- alias: Fan - Living Room Fans Med to Low Pico Remote Lower

  trigger:
    - platform: state
      entity_id: sensor.living_room_fan_remote
      to: '16'

  condition:
    - condition: state
      entity_id: group.living_room_fans
      state: 'on'
    - condition: or
      conditions:
      - condition: template
        value_template: "{%if is_state_attr('fan.living_room_east', 'speed', 'medium') %}true{%endif%}"
      - condition: template
        value_template: "{%if is_state_attr('fan.living_room_west', 'speed', 'medium') %}true{%endif%}"

  action:
    - service: fan.set_speed
      data:
        entity_id:
          - fan.living_room_east
          - fan.living_room_west
        speed: low
    - delay:
        seconds: 1

  #################################################################
  ## Living Room Fans Low to Off Pico Remote Lower
  #################################################################

- alias: Fan - Living Room Fans Low to Off Pico Remote Lower

  trigger:
    - platform: state
      entity_id: sensor.living_room_fan_remote
      to: '16'

  condition:
    - condition: state
      entity_id: group.living_room_fans
      state: 'on'
    - condition: or
      conditions:
      - condition: template
        value_template: "{%if is_state_attr('fan.living_room_east', 'speed', 'low') %}true{%endif%}"
      - condition: template
        value_template: "{%if is_state_attr('fan.living_room_west', 'speed', 'low') %}true{%endif%}"

  action:
    - service: fan.turn_off
      entity_id:
        - fan.living_room_east
        - fan.living_room_west
    - delay:
        seconds: 1
