#################################################################
## Garage Automations
#################################################################

        ##########################################################
        ## Household Away Mode Close Garage
        ##########################################################

- alias: Garage - Household Away Mode Close Garage

  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: cover.garage_door
      state: 'open'

  action:
    - service: lifx.effect_pulse
      data:
       entity_id: light.garage_interior
       cycles: '5'
    - delay: '00:00:05'
    - service: cover.close_cover
      entity_id: cover.garage_door

        ##########################################################
        ## USER1 Home from Driving Open Garage Door
        ##########################################################

- alias: Garage - USER1 Home from Driving Open Garage Door

  trigger:
    - platform: state
      entity_id: person.USER1
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_garage
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER1_away
      state: 'on'
    - condition: state
      entity_id: input_boolean.USER1_away_driving
      state: 'on'
    - condition: state
      entity_id: cover.garage_door
      state: 'closed'

  action:
    - service: cover.open_cover
      entity_id: cover.garage_door

        ##########################################################
        ## After USER1 Home Close Garage Door
        ########################################################

- alias: Garage - USER1 Home Close Garage

  trigger:
    - platform: state
      entity_id: input_boolean.USER1_away
      from: 'on'
      to: 'off'

  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_garage
      state: 'off'
    - condition: state
      entity_id: cover.garage_door
      state: 'open'

  action:
    - service: lifx.effect_pulse
      data:
       entity_id: light.garage_interior
       cycles: '5'
    - delay: '00:00:05'
    - service: cover.close_cover
      entity_id: cover.garage_door

        ##########################################################
        ## USER2 Home from Driving Open Garage
        ##########################################################

- alias: Garage - USER2 Home from Driving Open Garage

  trigger:
    - platform: state
      entity_id: person.USER2
#      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_garage
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER2_away
      state: 'on'
    - condition: state
      entity_id: input_boolean.USER2_away_driving
      state: 'on'
    - condition: state
      entity_id: cover.garage_door
      state: 'closed'

  action:
    - service: cover.open_cover
      entity_id: cover.garage_door

        ##########################################################
        ## After USER2 Home Close Garage Door
        ########################################################

- alias: Garage - USER2 Home Close Garage

  trigger:
    - platform: state
      entity_id: input_boolean.USER2_away
      from: 'on'
      to: 'off'

  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_garage
      state: 'off'
    - condition: state
      entity_id: cover.garage_door
      state: 'open'

  action:
    - service: lifx.effect_pulse
      data:
       entity_id: light.garage_interior
       cycles: '5'
    - delay: '00:00:05'
    - service: cover.close_cover
      entity_id: cover.garage_door

        ##########################################################
        ## Close Garage Door after 30 Mins
        ##########################################################

- alias: Garage - Close After 30 Mins

  trigger:
    - platform: state
      entity_id: cover.garage_door
      to: 'open'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_garage
      state: 'off'
    - condition: state
      entity_id: cover.garage_door
      state: 'open'

  action:
    - service: lifx.effect_pulse
      data:
       entity_id: light.garage_interior
       cycles: '5'
    - delay: '00:00:05'
    - service: cover.close_cover
      entity_id: cover.garage_door

        ##########################################################
        ## Garage Door Open on Demand (Echo Integration)
        ##########################################################

- alias: Garage - Open on Demand

  trigger:
    - platform: state
      entity_id: input_boolean.garage_door
      to: 'on'

  condition:
    - condition: state
      entity_id: cover.garage_door
      state: 'closed'

  action:
    - service: cover.open_cover
      entity_id: cover.garage_door

        ##########################################################
        ## Garage Door Close on Demand (Echo Integration)
        ##########################################################

- alias: Garage - Close on Demand

  trigger:
    - platform: state
      entity_id: input_boolean.garage_door
      to: 'off'

  condition:
    - condition: state
      entity_id: cover.garage_door
      state: 'open'

  action:
    - service: lifx.effect_pulse
      data:
       entity_id: light.garage_interior
       cycles: '5'
    - delay: '00:00:05'
    - service: cover.close_cover
      entity_id: cover.garage_door

        ##########################################################
        ## Turn off Garage Door Boolean when Closed
        ##########################################################

- alias: Garage - Turn off Garage Door Boolean when Closed

  trigger:
    - platform: state
      entity_id: cover.garage_door
      from: 'open'
      to: 'closed'

  condition:
    - condition: state
      entity_id: cover.garage_door
      state: 'closed'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.garage_door

        ##########################################################
        ## Turn on Garage Door Boolean when Open
        ##########################################################

- alias: Garage - Turn on Garage Door Boolean when Open

  trigger:
    - platform: state
      entity_id: cover.garage_door
      from: 'closed'
      to: 'open'

  condition:
    - condition: state
      entity_id: cover.garage_door
      state: 'open'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.garage_door

        ##########################################################
        ## Open Garage Door when USER2 Leaves for Work
        ##########################################################

- alias: Garage - USER2 Leaving for Work Open Garage

  trigger:
    - platform: state
      entity_id: binary_sensor.back_door_opened
      from: 'off'
      to: 'on'

  condition:
    - condition: time
      after: '06:00'
      before: '07:30'
    - condition: state
      entity_id: input_boolean.disable_auto_garage
      state: 'off'
    - condition: state
      entity_id: person.USER2
      state: 'home'
    - condition: state
      entity_id: input_boolean.USER2_away
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: cover.garage_door
      state: 'closed'

  action:
    - service: cover.open_cover
      entity_id: cover.garage_door

        ##########################################################
        ## Flash Light When Garage Door Closes
        ##########################################################

- alias: Garage - Flash Light When Garage Door Closes

  trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: cover
        service: close_cover

  condition:
    - condition: state
      entity_id: cover.garage_door
      state: 'open'
    - condition: state
      entity_id: light.garage_interior
      state: 'on'

  action:
    - service: lifx.effect_pulse
      data:
       entity_id: light.garage_interior
       cycles: '5'

#################################################################
## Notifications
#################################################################

        #################################################################
        ## Garage Open iOS Notification
        #################################################################

- alias: Garage - Garage Open iOS Notification

  trigger:
    - platform: state
      entity_id: cover.garage_door
      from: 'closed'
      to: 'open'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: Garage Door Open
        data:
          apns_headers:
           'apns-collapse-id': 'garage-garage-camera'
          push:
            category: camera
          entity_id: camera.garage

        #################################################################
        ## Garage Closed iOS Notification
        #################################################################

- alias: Garage - Garage Closed iOS Notification

  trigger:
    - platform: state
      entity_id: cover.garage_door
      from: 'open'
      to: 'closed'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: Garage Door Closed
        data:
          apns_headers:
           'apns-collapse-id': 'garage-garage-camera'
          push:
            category: camera
          entity_id: camera.garage

        #################################################################
        ## Garage Door Still Open iOS Notification
        #################################################################

- alias: Garage - Garage Door Still Open iOS Notification

  trigger:
    - platform: state
      entity_id: cover.garage_door
      to: 'open'
      for:
        hours: 0
        minutes: 35
        seconds: 0
    - platform: state
      entity_id: cover.garage_door
      to: 'closing'
      for:
        hours: 0
        minutes: 10
        seconds: 0
    - platform: state
      entity_id: cover.garage_door
      to: 'opening'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: Garage Door is Still Open!
        data:
          apns_headers:
           'apns-collapse-id': 'garage-garage-camera'
          push:
            category: camera
          entity_id: camera.garage
    - service: notify.mobile_app_USER2_s_iphone
      data:
        message: Garage Door is Still Open!
        data:
          apns_headers:
           'apns-collapse-id': 'garage-garage-camera'
          push:
            category: camera
          entity_id: camera.garage
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: Garage Door Still Open Close It?
        data:
          apns_headers:
           'apns-collapse-id': 'garage-open'
          push:
            badge: 0
            category: "garage"
    - service: notify.mobile_app_USER2_s_iphone
      data:
        message: Garage Door Still Open Close It?
        data:
          apns_headers:
           'apns-collapse-id': 'garage-open'
          push:
            badge: 0
            category: "garage"
