#################################################################
## Garage Automations
#################################################################

        ##########################################################
        ## Close Garage Door after 30 Mins
        ##########################################################

- alias: Garage - Close After 30 Mins

  trigger:
    - platform: state
      entity_id: cover.garage_door
      to: 'open'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_garage
      state: 'off'

  action:
    - service: cover.close_cover
      entity_id: cover.garage_door


        ##########################################################
        ## Garage Door Open on Demand (Echo Integration)
        ##########################################################

- alias: Garage - Open on Demand

  trigger:
    - platform: state
      entity_id: input_boolean.garage_door
      to: 'on'

  condition:
    - condition: state
      entity_id: cover.garage_door
      state: 'closed'

  action:
    - service: cover.open_cover
      entity_id: cover.garage_door

        ##########################################################
        ## Garage Door Close on Demand (Echo Integration)
        ##########################################################

- alias: Garage - Close on Demand

  trigger:
    - platform: state
      entity_id: input_boolean.garage_door
      to: 'off'

  condition:
    - condition: state
      entity_id: cover.garage_door
      state: 'open'

  action:
    - service: cover.close_cover
      entity_id: cover.garage_door

        ##########################################################
        ## Reset Dummy Garage Door Switch
        ##########################################################

- alias: Garage - Reset Dummy Switch when Closed

  trigger:
    - platform: state
      entity_id: cover.garage_door
      to: 'closed'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.garage_door

- alias: Turn on Garage Door when Open

  trigger:
    - platform: state
      entity_id: cover.garage_door
      to: 'open'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.garage_door

        ##########################################################
        ## Open Garage Door when USER2 Leaves for Work
        ##########################################################

- alias: Garage - USER2 Leaving for Work Open Garage

  trigger:
    - platform: state
      entity_id: binary_sensor.back_door_opened
      from: 'off'
      to: 'on'

  condition:
    - condition: time
      after: '06:00'
      before: '07:30'
    - condition: state
      entity_id: input_boolean.disable_auto_garage
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER2_away
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: cover.open_cover
      entity_id: cover.garage_door

        ##########################################################
         ## Power Cycle Opener Outlet if not Closed in 60 Mins
         ##########################################################

- alias: Garage - Power Cycle Opener Outlet if not Closed in 60 Mins

  trigger:
   - platform: state
     entity_id: cover.garage_door
     to: 'open'
     for:
       hours: 0
       minutes: 60
       seconds: 0

  condition:
   - condition: state
     entity_id: input_boolean.disable_auto_garage
     state: 'off'

  action:
   - service: switch.turn_off
     entity_id:
       - switch.garage_door_opener_outlet
   - delay: '00:00:60'
   - service: switch.turn_on
     entity_id:
       - switch.garage_door_opener_outlet
   - delay: '00:02:00'
   - service: cover.close_cover
     entity_id: cover.garage_door
   - delay: '00:00:30'
   - service: notify.ios_USER1
     data:
       message: Garage Door Did not Close, Power Cycling Opener
       data:
         push:
           category: camera
         entity_id: camera.garage
