#################################################################
## iOS Actions
#################################################################

        #################################################################
        ## Bedtime
        #################################################################

- alias: iOS Action - Bedtime
  id: 'ios_action_bedtime'

  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Bedtime'

  action:
    - service: homeassistant.turn_on
      entity_id:
        - input_boolean.bedtime

        #################################################################
        ## Arm Alarm Home
        #################################################################

- alias: iOS Action - Arm Alarm Home
  id: 'ios_action_arm_alarm_home'

  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Arm Alarm Home'

  action:
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.alarm

        #################################################################
        ## Arm Alarm Away
        #################################################################

- alias: iOS Action - Arm Alarm Away
  id: 'ios_action_arm_alarm_away'

  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Arm Alarm Away'

  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.alarm

        #################################################################
        ## Disarm Alarm
        #################################################################

- alias: iOS Action - Disarm Alarm
  id: 'ios_action_disarm_alarm'

  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Disarm Alarm'

  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm

#################################################################
## iOS Actionable Notifications
#################################################################

        #################################################################
        ## Unlock Doors
        #################################################################

- alias: iOS Action - Unlock Doors
  id: 'ios_action_unlock_doors'

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: UNLOCK_DOORS

  action:
    - service: lock.unlock
      entity_id:
        - lock.back_door
        - lock.front_door

        #################################################################
        ## Lock Doors
        #################################################################

- alias: iOS Action - Lock Doors
  id: 'ios_action_lock_doors'

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: LOCK_DOORS

  action:
    - service: lock.lock
      entity_id:
       - lock.front_door
       - lock.back_door
       - lock.basement_door

        #################################################################
        ## Unlock Front Door
        #################################################################

- alias: iOS Action - Unlock Front Door
  id: 'ios_action_unlock_front_door'

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: FRONT_DOOR_UNLOCK

  action:
    - service: lock.unlock
      entity_id:
        - lock.front_door

        #################################################################
        ## Close Garage
        #################################################################

- alias: iOS Action - Close Garage
  id: 'ios_action_close_garage'

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: CLOSE_GARAGE

  action:
    - service: cover.close_cover
      entity_id: cover.garage_door

        #################################################################
        ## Open Garage
        #################################################################

- alias: iOS Action - Open Garage
  id: 'ios_action_open_garage'

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: OPEN_GARAGE

  action:
    - service: cover.open_cover
      entity_id: cover.garage_door

        #################################################################
        ## Sound Alarm
        #################################################################

- alias: iOS Action - Sound Alarm
  id: 'ios_action_sound_alarm'

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SOUND_ALARM

  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm

        #################################################################
        ## Silence Alarm
        #################################################################

- alias: iOS Action - Silence Alarm
  id: 'ios_action_silence_alarm'

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SILENCE_ALARM

  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm

        #################################################################
        ## Disable Alarm
        #################################################################

- alias: iOS Action - Disable Alarm
  id: 'ios_action_disable_alarm'

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DISABLE_ALARM

  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm

        #################################################################
        ## Enable Alarm
        #################################################################

- alias: iOS Action - Enable Alarm
  id: 'ios_action_enable_alarm'

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: ENABLEALARM

  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.alarm

        #################################################################
        ## Siren
        #################################################################

- alias: iOS Action - Siren
  id: 'ios_action_siren'

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SIREN

  action:
    - service: switch.turn_off
      entity_id: switch.siren

        #################################################################
        ## Fireplace Off
        #################################################################

- alias: iOS Action - Fireplace Off
  id: 'ios_action_fireplace_off'

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: FIREPLACE_OFF

  action:
    - service: switch.turn_off
      entity_id: switch.fireplace

        #################################################################
        ## Disable Fire Alarm
        #################################################################

- alias: iOS Action - Disable Smoke Alarm
  id: 'ios_action_disable_smoke_alarm'

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SMOKEALARM_OFF

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.disable_smoke_alarm

        #################################################################
        ## Washing Machine Done Turn On Lights
        #################################################################

- alias: iOS Action - Washing Machine Done Turn On Lights
  id: 'ios_action_washing_machine_done_turn_on_lights'

  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: WASHINGMACHINE_DONE_LIGHTS

  action:
    - service: light.turn_on
      entity_id:
        - light.laundry_room_light
