#################################################################
## Laundry Automations
#################################################################

        ##########################################################
        ## Shut off Washer and Dryer if Water Detected
        ##########################################################

#- alias: Laundry - Shut off Washer and Dryer if Water Detected

#  trigger:
#    - platform: state
#      entity_id: binary_sensor.basement_drain_water_sensor_liquid_detected
#      from: 'off'
#      to: 'on'
#    - platform: state
#      entity_id: binary_sensor.washing_machine_water_sensor
#      from: 'off'
#      to: 'on'

#  condition:
#    - condition: state
#      entity_id: input_boolean.disable_water_automations
#      state: 'off'

#  action:
#    - service: switch.turn_off
#      entity_id:
#        - switch.washing_machine
#        - switch.dryer

        #################################################################
        ## Turn On Washing Machine if Off on Startup
        #################################################################

#- alias: Laundry - Turn on Washing Machine if Off on Startup

#  trigger:
#    - platform: homeassistant
#      event: start

#  condition:
#    - condition: state
#      entity_id: switch.washing_machine
#      state: 'off'

#  action:
#    - service: switch.turn_on
#      entity_id:
#        - switch.washing_machine

        #################################################################
        ## Turn On Dryer if Off on Startup
        #################################################################

#- alias: Laundry - Turn on Dryer if Off on Startup

#  trigger:
#    - platform: homeassistant
#      event: start

#  condition:
#    - condition: state
#      entity_id: switch.dryer
#      state: 'off'

#  action:
#    - service: switch.turn_on
#      entity_id:
#        - switch.dryer

#################################################################
## Notifications
#################################################################

        ##########################################################
        ## Washing Machine Done - USER1 iOS Notification
        ##########################################################

- alias: Laundry - Washing Machine Done USER1 iOS Notification

  trigger:
    - platform: state
#     entity_id: binary_sensor.washing_machine_status
      entity_id: sensor.washer
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 15

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: Washing Machine Finished
        data:
          apns_headers:
           'apns-collapse-id': 'laundry-done'
          push:
            badge: 0
            category: "washingmachinedonelights"

        ##########################################################
        ## Dryer Done - USER1 iOS Notification
        ##########################################################

- alias: Laundry - Dryer Done USER1 iOS Notification

  trigger:
    - platform: state
#     entity_id: binary_sensor.dryer_status
      entity_id: sensor.dryer
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 15

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: Dryer Finished
        data:
          apns_headers:
           'apns-collapse-id': 'laundry-done'
          push:
            badge: 0
            category: "washingmachinedonelights"

        ##########################################################
        ## Washing Machine Done - USER2 iOS Notification
        ##########################################################

- alias: Laundry - Washing Machine Done USER2 iOS Notification

  trigger:
    - platform: state
#     entity_id: binary_sensor.washing_machine_status
      entity_id: sensor.washer
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 15

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER2
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER2_s_iphone
      data:
        message: Washing Machine Finished
        data:
          apns_headers:
           'apns-collapse-id': 'laundry-done'
          push:
            badge: 0
            category: "washingmachinedonelights"

        ##########################################################
        ## Dryer Done - USER2 iOS Notification
        ##########################################################

- alias: Laundry - Dryer Done USER2 iOS Notification

  trigger:
    - platform: state
#     entity_id: binary_sensor.dryer_status
      entity_id: sensor.dryer
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 15

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER2
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER2_s_iphone
      data:
        message: Dryer Finished
        data:
          apns_headers:
           'apns-collapse-id': 'laundry-done'
          push:
            badge: 0
            category: "washingmachinedonelights"

        ##########################################################
        ## Washing Machine Switch Off iOS Notification
        ##########################################################

#- alias: Laundry - Washing Machine Switch Off iOS Notification

#  trigger:
#    - platform: state
#      entity_id: switch.washing_machine
#      from: 'on'
#      to: 'off'

#  condition:
#    - condition: state
#      entity_id: input_boolean.disable_notifications
#      state: 'off'

#  action:
#    - service: notify.mobile_app_USER1s_iphone
#      data:
#        message: Washing Machine Switch Turned Off!
#        data:
#          apns_headers:
#           'apns-collapse-id': 'laundry-switch'
#          push:
#            badge: 0
#            category: "washingmachineswitch"

        ##########################################################
        ## Dryer Switch Off iOS Notification
        ##########################################################

#- alias: Laundry - Dryer Switch Off iOS Notification

#  trigger:
#    - platform: state
#      entity_id: switch.dryer
#      from: 'on'
#      to: 'off'

#  condition:
#    - condition: state
#      entity_id: input_boolean.disable_notifications
#      state: 'off'

#  action:
#    - service: notify.mobile_app_USER1s_iphone
#      data:
#        message: Dryer Switch Turned Off!
#        data:
#          apns_headers:
#           'apns-collapse-id': 'laundry-switch'
#          push:
#            badge: 0
#            category: "dryerswitch"

        ##########################################################
        ## Washing Machine Done - Audio Notification
        ##########################################################

- alias: Laundry - Washing Machine Done Audio Notification

  trigger:
    - platform: state
#     entity_id: binary_sensor.washing_machine_status
      entity_id: sensor.washer
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: time
      after: '09:00'
      before: '20:30'

  action:
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen, media_player.sonos_USER1s_office, media_player.sonos_USER1s_office_move, media_player.sonos_USER2s_office'
          volume: '0.5'
          what: 'Washing Machine Has Finished'

        ##########################################################
        ## Dryer Done - Audio Notification
        ##########################################################

- alias: Laundry - Dryer Done Audio Notification

  trigger:
    - platform: state
#     entity_id: binary_sensor.dryer_status
      entity_id: sensor.dryer
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: time
      after: '09:00'
      before: '20:30'

  action:
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen, media_player.sonos_USER1s_office, media_player.sonos_USER1s_office_move, media_player.sonos_USER2s_office'
          volume: '0.5'
          what: 'Dryer Has Finished'
