#################################################################
## Laundry Automations
#################################################################

#################################################################
## Notifications
#################################################################

        ##########################################################
        ## Washing Machine Done - USER1 iOS Notification
        ##########################################################

- alias: Laundry - Washing Machine Done USER1 iOS Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.washer_wash_completed
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 1

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: Washing Machine Finished
        data:
          apns_headers:
           'apns-collapse-id': 'laundry-done'
          push:
            badge: 0
            category: "washingmachinedonelights"

        ##########################################################
        ## Dryer Done - USER1 iOS Notification
        ##########################################################

- alias: Laundry - Dryer Done USER1 iOS Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.dryer_dry_completed
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 1

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: Dryer Finished
        data:
          apns_headers:
           'apns-collapse-id': 'laundry-done'
          push:
            badge: 0
            category: "washingmachinedonelights"

        ##########################################################
        ## Washing Machine Done - USER2 iOS Notification
        ##########################################################

- alias: Laundry - Washing Machine Done USER2 iOS Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.washer_wash_completed
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 1

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER2
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER2_s_iphone
      data:
        message: Washing Machine Finished
        data:
          apns_headers:
           'apns-collapse-id': 'laundry-done'
          push:
            badge: 0
            category: "washingmachinedonelights"

        ##########################################################
        ## Dryer Done - USER2 iOS Notification
        ##########################################################

- alias: Laundry - Dryer Done USER2 iOS Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.dryer_dry_completed
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 1

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER2
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER2_s_iphone
      data:
        message: Dryer Finished
        data:
          apns_headers:
           'apns-collapse-id': 'laundry-done'
          push:
            badge: 0
            category: "washingmachinedonelights"

        ##########################################################
        ## Washing Machine Done - Audio Notification
        ##########################################################

- alias: Laundry - Washing Machine Done Audio Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.washer_wash_completed
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 1

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: time
      after: '09:00:00'
      before: '20:00:00'

  action:
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen, media_player.sonos_USER1s_office, media_player.sonos_USER1s_office_move, media_player.sonos_USER2s_office'
          volume: 0.5
          what: 'Washing Machine Has Finished'

        ##########################################################
        ## Dryer Done - Audio Notification
        ##########################################################

- alias: Laundry - Dryer Done Audio Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.dryer_dry_completed
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 1

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: time
      after: '09:00:00'
      before: '20:00:00'

  action:
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen, media_player.sonos_USER1s_office, media_player.sonos_USER1s_office_move, media_player.sonos_USER2s_office'
          volume: 0.5
          what: 'Dryer Has Finished'

        ##########################################################
        ## Washer Run Tub Clean Notification
        ##########################################################

- alias: Laundry - Washer Run Tub Clean Notification

  trigger:
    - platform: numeric_state
      entity_id: sensor.washer_tub_clean
      above: 29

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER2_s_iphone
      data:
        message: Time to Run a Tub Clean Cycler on the Washer
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: Time to Run a Tub Clean Cycler on the Washer
