#################################################################
## Text Notification Automations
#################################################################

    #################################################################
    ## Alarm Notifications
    #################################################################

- alias: Notification Text - Security

  trigger:
    - platform: state
      entity_id: input_boolean.alarm_tripped
      from: 'off'
      to: 'on'

  action:
    - service: persistent_notification.create
      data:
        message: "Alarm Has Been Tripped!"
        title: "Alarm"
        notification_id: "1"


- alias: Notification Text - Alarm

  trigger:
    - platform: state
      entity_id: input_boolean.alarm_tripped
      from: 'off'
      to: 'on'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Alarm Tripped
        data:
          push:
            category: camera
          entity_id: camera.garage

        #################################################################
        ## USER1 Home Notification
        #################################################################

- alias: Notification Text - USER1 Home

  trigger:
    - platform: state
      entity_id: device_tracker.USER1DEVICE
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.USER1_away
      state: 'on'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: USER1 Home
        data:
          push:
            category: camera
          entity_id: camera.garage
    - service: notify.ios_USER2s_iphone
      data:
        message: USER1 Home
        data:
          push:
            category: camera
          entity_id: camera.garage


        #################################################################
        ## USER1 Away Notification
        #################################################################

- alias: Notification Text - USER1 Away

  trigger:
    - platform: state
      entity_id: device_tracker.USER1DEVICE
      from: 'home'
      to: 'not_home'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: USER1 Away

        #################################################################
        ## USER2 Home Notification
        #################################################################

- alias: Notification Text - USER2 Home

  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.USER2_away
      state: 'on'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: USER2 Home
        data:
          push:
            category: camera
          entity_id: camera.garage


        #################################################################
        ## USER2 Away Notification
        #################################################################

- alias: Notification Text - USER2 Away

  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'home'
      to: 'not_home'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: USER2 Away

        #################################################################
        ## USER2 Left Work Notification
        #################################################################

- alias: Notification Text - USER2 Left Work

  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'work'
      to: 'not_home'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: USER2 has left Work

        #################################################################
        ## Motion Alarm Notification
        #################################################################

- alias: Notification Text - Motion Based Alarm

  trigger:
    - platform: state
      entity_id: group.alarm_occupancy
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Motion Detected Alarm!
        data:
          push:
            category: camera
          entity_id: camera.garage
    - service: notify.ios_USER2s_iphone
      data:
        message: Motion Detected Alarm!
        data:
          push:
            category: camera
          entity_id: camera.garage


        #################################################################
        ## Door Alarm Notification
        #################################################################

- alias: Notification Text - Door Open Alarm

  trigger:
    - platform: state
      entity_id: group.doors
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Door Opened Alarm!
        data:
          push:
            category: camera
          entity_id: camera.garage
    - service: notify.ios_USER2s_iphone
      data:
        message: Door Opened Alarm!
        data:
          push:
            category: camera
          entity_id: camera.garage

        #################################################################
        ## Fireplace Alarm Notification
        #################################################################

- alias: Notification Text - Fireplace On when Nobody Home

  trigger:
    - platform: state
      entity_id: switch.fireplace
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Fireplace Turned On!

        #################################################################
        ## Garage Door Still Open Notification
        #################################################################

- alias: Notification Text - Garage Door Still Open

  trigger:
    - platform: state
      entity_id: cover.garage_door
      from: 'closed'
      to: 'open'
      for:
        hours: 0
        minutes: 35
        seconds: 0

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Garage Door is Still Open!
        data:
          push:
            category: camera
          entity_id: camera.garage_interior
    - service: notify.ios_USER2s_iphone
      data:
        message: Garage Door is Still Open!
        data:
          push:
            category: camera
          entity_id: camera.garage_interior

        #################################################################
        ## Weather Lookup Failing
        #################################################################

- alias: Notification Text - Weather Lookup Failing

  trigger:
    - platform: state
      entity_id: sensor.dark_sky_humidity
      to: 'unknown'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Weather Lookup Problem!

        #################################################################
        ## NAS Warning
        #################################################################

- alias: Notification Text - NAS Warning

  trigger:
    - platform: state
      entity_id: sensor.nas_status
      to: 'warning'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: NAS RAID Failing

        #################################################################
        ## Home Assistant Started Notification
        #################################################################

- alias: Notification Text - Home Assistant Start

  trigger:
    - platform: homeassistant
      event: start

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Home Assistant Started
