#################################################################
## Occupancy Automations
#################################################################

        ##########################################################
        ## Turn off Bedroom when Unoccupied
        ##########################################################

- alias: Occupancy - Turn off Bedroom Lights when Unoccupied

  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_occupancy
      from: 'on'
      to: 'off'
      for:
        hours: 1
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_occupancy
      state: 'off'

  action:
    - service: light.turn_off
      entity_id: light.bedroom_lights

        ##########################################################
        ## Turn off Guest Bedroom when Unoccupied
        ##########################################################

- alias: Occupancy - Turn off Guest Bedroom Lights when Unoccupied

  trigger:
    - platform: state
      entity_id: binary_sensor.guest_bedroom_occupancy
      from: 'on'
      to: 'off'
      for:
        hours: 1
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_occupancy
      state: 'off'

  action:
    - service: light.turn_off
      entity_id: light.guest_bedroom_lights
