        ##########################################################
        ## Run Roomba when Away
        ##########################################################

- alias: Roomba - Run Roomba when Away

  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: time
      after: '10:01'
      before: '23:59'
    - condition: state
      entity_id: vacuum.roomba
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.roomba_batt
      above: 99

  action:
    - service: vacuum.turn_on
      entity_id:
        - vacuum.roomba

        ##########################################################
        ## Shut Off Roomba when Home
        ##########################################################

- alias: Roomba - Shut Off Roomba when Home

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: vacuum.roomba
      state: 'on'

  action:
    - service: vacuum.return_to_base
      entity_id:
        - vacuum.roomba

        ##########################################################
        ## Run Roomba Weekdays
        ##########################################################

- alias: Roomba - Run Roomba Weekdays

  trigger:
   - platform: time
     at: '10:00'

  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: vacuum.roomba
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: device_tracker.USER2DEVICE
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.USER2DEVICE
        state: 'work'

  action:
    - service: vacuum.turn_on
      entity_id:
        - vacuum.roomba

        ##########################################################
        ## Run Roomba Weekends
        ##########################################################

- alias: Roomba - Run Roomba Weekends

  trigger:
   - platform: time
     at: '13:00'

  condition:
    - condition: time
      weekday:
        - sat
        - sun
    - condition: state
      entity_id: vacuum.roomba
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.roomba_batt
      above: 99
    - condition: or
      conditions:
      - condition: state
        entity_id: device_tracker.USER2DEVICE
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.USER2DEVICE
        state: 'work'

  action:
    - service: vacuum.turn_on
      entity_id:
        - vacuum.roomba

        ##########################################################
        ## Turn on low lights at night for Roomba
        ##########################################################

- alias: Roomba - Turn on low lights at night for Roomba

  trigger:
    - platform: state
      entity_id: vacuum.roomba
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  action:
    - service: light.turn_on
      entity_id:
        - group.bedroom_lights
        - group.stairs
        - light.hallway_light
        - light.basement_stairs
      data:
       brightness_pct: 25
       profile: relax
    - service: light.turn_on
      entity_id:
        - group.living_room_lights
      data:
       brightness_pct: 50
       profile: relax
    - service: light.turn_on
      entity_id:
        - light.dining_room_table
        - light.bathroom_vanity
        - light.kitchen_sink
        - light.kitchen_cabinets
      data:
       brightness_pct: 1

        ##########################################################
        ## Turn off lights at night when Roomba finished
        ##########################################################

- alias: Roomba - Turn off lights at night when Roomba finished

  trigger:
    - platform: state
      entity_id: vacuum.roomba
      from: 'on'
      to: 'off'

  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  action:
    - service: light.turn_off
      entity_id:
        - group.interior_lights

        ##########################################################
        ## Run Roomba when USER2 Leaves
        ##########################################################

- alias: Roomba - Run Roomba when USER2 Leaves

  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: time
      after: '10:01'
      before: '17:00'
    - condition: state
      entity_id: vacuum.roomba
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.roomba_batt
      above: 99
    - condition: state
      entity_id: input_boolean.USER1_away
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: vacuum.turn_on
      entity_id:
        - vacuum.roomba

        ##########################################################
        ## Turn off Roomba when USER2 Home
        ##########################################################

- alias: Roomba - Turn off Roomba when USER2 Home

  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: time
      after: '10:01'
      before: '18:30'
    - condition: state
      entity_id: vacuum.roomba
      state: 'on'
    - condition: state
      entity_id: input_boolean.USER1_away
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER2_away
      state: 'on'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: vacuum.return_to_base
      entity_id:
        - vacuum.roomba

        ##########################################################
        ## Roomba is Stuck Notification
        ##########################################################

- alias: Roomba - Stuck Notification

  trigger:
    - platform: template
      value_template: "{%if is_state_attr('vacuum.roomba', 'status', 'Stuck') %}true{%endif%}"

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Roomba is Stuck, Please Help

        ##########################################################
        ## Roomba is Full Notification
        ##########################################################

- alias: Roomba - Full Notification

  trigger:
    - platform: template
      value_template: "{%if is_state_attr('vacuum.roomba', 'bin_full', true) %}true{%endif%}"

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Roomba is Full, Empty It
