#################################################################
## Save Current State Automations
#################################################################

        ##########################################################
        ## Save Current States on Change
        ##########################################################

- alias: Save States - Save

  trigger:
    - platform: state
      entity_id: input_boolean.thermostat_away
    - platform: state
      entity_id: input_boolean.USER1_away
    - platform: state
      entity_id: input_boolean.USER1_away_driving
    - platform: state
      entity_id: input_boolean.USER1_greeting
    - platform: state
      entity_id: input_boolean.USER2_away
    - platform: state
      entity_id: input_boolean.USER2_away_driving
    - platform: state
      entity_id: input_boolean.USER2_greeting
    - platform: state
      entity_id: input_boolean.enable_security
    - platform: state
      entity_id: input_boolean.vacation_mode
    - platform: state
      entity_id: input_boolean.disable_home_away
    - platform: state
      entity_id: input_boolean.garage_door
    - platform: state
      entity_id: input_select.holiday
    - platform: state
      entity_id: input_select.remote
    - platform: state
      entity_id: device_tracker.USER1DEVICE
    - platform: state
      entity_id: device_tracker.USER2DEVICE

  action:
    - service: shell_command.export_ha_states
      data_template:
        section: '{{ trigger.entity_id }}'
        settings: '{{ trigger.entity_id }}'
        value: "{{ trigger.to_state.state }}"

        ##########################################################
        ## Load States on Startup
        ##########################################################

- alias: Save States - Load

  trigger:
    - platform: event
      event_type: homeassistant_start

  action:
    - delay: 00:01:30
    - service: shell_command.import_ha_states
