#################################################################
## Vacation Mode Automations
#################################################################

        ##########################################################
        ## Vacation Mode On
        ##########################################################

- alias: Vacation - Vacation Mode On

  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: 'on'

  condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: group.household
        state: 'home'
    - condition: not
      conditions:
      - condition: state
        entity_id: group.friends_and_family
        state: 'home'

  action:
    - service: homeassistant.turn_on
      entity_id:
       - input_boolean.disable_rainy_day
       - input_boolean.disable_interior_lights_sunset
       - input_boolean.disable_media_lights
       - input_boolean.disable_occupancy
       - input_boolean.disable_motion

        ##########################################################
        ## Vacation Mode Off
        ##########################################################

- alias: Vacation - Vacation Mode On

  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: 'off'

  action:
    - service: homeassistant.turn_off
      entity_id:
       - input_boolean.disable_rainy_day
       - input_boolean.disable_interior_lights_sunset
       - input_boolean.disable_media_lights
       - input_boolean.disable_occupancy
       - input_boolean.thermostat_away
       - input_boolean.disable_motion

        ##########################################################
        ## Turn on Vacation Mode when Gone 24 Hours
        ##########################################################

- alias: Vacation - Turn on when Gone 24 Hours

  trigger:
    - platform: state
      entity_id: group.household
      to: 'not_home'
      for:
        hours: 24
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacation_mode

        ##########################################################
        ## Turn off Vacation Mode when Home
        ##########################################################

- alias: Vacation - Turn off when Home

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.vacation_mode

        ##########################################################
        ## Turn on Vacation Mode when Thermostat set to Vacation
        ##########################################################

- alias: Vacation - Turn on Vacation Mode when Thermostat set to Vacation

  trigger:
    - platform: state
      entity_id: sensor.thermostat_climate_mode
      to: 'vacation'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: group.household
        state: 'home'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacation_mode

        ##########################################################
        ## Turn on Vacation Mode when at the Lake
        ##########################################################

- alias: Vacation - Turn on when at the Lake

  trigger:
    - platform: state
      entity_id: person.USER1
      from: 'not_home'
      to: 'Lake'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacation_mode

        ##########################################################
        ## Turn off Vacation Mode when leaving the Lake
        ##########################################################

- alias: Vacation - Turn off when leaving the Lake

  trigger:
    - platform: state
      entity_id: person.USER1
      from: 'Lake'
      to: 'not_home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.vacation_mode

        ##########################################################
        ## Vacation Lights on at Night
        ##########################################################

- alias: Vacation - Lights on at Night

  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'

  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'

  action:
    - service: light.turn_on
      entity_id:
        - light.USER1_s_office_ceiling
        - light.kitchen_sink
        - light.bedroom_closet_ceiling
      data:
        brightness_pct: 2
    - service: light.turn_on
      entity_id:
        - light.living_room_lamps
      data:
        brightness_pct: 25
        transition: 120

        ##########################################################
        ## Vacation Mode Lights off at Midnight
        ##########################################################

- alias: Vacation - Lights Off Midnight

  trigger:
    - platform: time
      at: '23:16:32'

  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'

  action:
    - service: light.turn_off
      entity_id:
        - light.kitchen_sink
    - delay: '00:10:04'
    - service: light.turn_off
      entity_id:
        - light.living_room_lamps

        ##########################################################
        ## Vacation Mode Lights off at 10p
        ##########################################################

- alias: Vacation - Lights Off 10p

  trigger:
    - platform: time
      at: '22:13:51'

  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'

  action:
    - service: light.turn_off
      entity_id:
        - light.bedroom_closet_ceiling
    - delay: '00:15:32'
    - service: light.turn_off
      entity_id:
        - light.USER1_s_office_ceiling
