#################################################################
## Weather Based Automations
#################################################################

        ##########################################################
        ## Turn On First Floor Lights when Raining
        ##########################################################

- alias: Weather - Rain First Floor Lights On

  trigger:
    - platform: state
      entity_id: sensor.dark_sky_precip
      to: 'rain'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: time
      after: '09:00'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: binary_sensor.main_floor_occupancy
      state: 'on'
    - condition: state
      entity_id: input_boolean.rainy_day_disable
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: light.turn_on
      entity_id: group.living_room_lamps, light.kitchen_cabinets, light.dining_room_table, light.media_center_lighting, light.hallway_light
      data:
        xy_color: [ 0.5134, 0.4149 ]
        brightness: 3

        ##########################################################
        ## Turn Off First Floor Lights when no Longer Raining
        ##########################################################

- alias: Weather - Rain is over First Floor Lights Off

  trigger:
    - platform: state
      entity_id: sensor.dark_sky_precip
      to: 'unknown'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.rainy_day_disable
      state: 'off'

  action:
    - service: light.turn_off
      entity_id: group.living_room_lamps, light.kitchen_cabinets, light.dining_room_table, light.media_center_lighting, light.hallway_light

        ##########################################################
        ## Turn On USER2 Office when Raining
        ##########################################################

- alias: Weather - Rain USER2 Office Lights On

  trigger:
    - platform: state
      entity_id: sensor.dark_sky_precip
      to: 'rain'

  condition:
    - condition: state
      entity_id: binary_sensor.USER2_office_occupancy
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: input_boolean.rainy_day_disable
      state: 'off'
    - condition: state
      entity_id: device_tracker.USER2DEVICE
      state: 'home'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: group.USER2_office
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: group.USER2_office, group.stairs
      data:
        transition: 300
        brightness: 255

        ##########################################################
        ## Turn Off USER2 Office when no Longer Raining
        ##########################################################

- alias: Weather - Rain is over USER2 Office Lights Off

  trigger:
    - platform: state
      entity_id: sensor.dark_sky_precip
      to: 'unknown'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.rainy_day_disable
      state: 'off'

  action:
    - service: light.turn_off
      entity_id: group.USER2_office, group.stairs
      data:
        transition: 900

        ##########################################################
        ## Turn On USER1 Office when Raining
        ##########################################################

- alias: Weather - Rain USER1 Office Lights On

  trigger:
    - platform: state
      entity_id: sensor.dark_sky_precip
      to: 'rain'

  condition:
    - condition: state
      entity_id: binary_sensor.office_occupancy
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: input_boolean.rainy_day_disable
      state: 'off'
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'home'
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: light.turn_on
      entity_id: light.office_lamp, group.stairs
      data:
        brightness: 3
        xy_color: [0.139,0.081]

        ##########################################################
        ## Turn Off USER1 Office when no Longer Raining
        ##########################################################

- alias: Weather - Rain is over USER1 Office Lights Off

  trigger:
    - platform: state
      entity_id: sensor.dark_sky_precip
      to: 'unknown'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.rainy_day_disable
      state: 'off'

  action:
    - service: light.turn_off
      entity_id: light.office_lamp, group.stairs
